#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

case "$1" in

  purge)
    # Remove the Debian system user/group.
    deluser --quiet --remove-home oversip &>/dev/null || true

    # Remove the Ruby gem.
    echo "uninstalling 'oversip' Ruby Gem(s)..."
    gem uninstall oversip -a -x
    
    # Clean up any leftover binary in /usr/local/bin (from old installations)
    if [ -f /usr/local/bin/oversip ]; then
      echo "Removing leftover binary from /usr/local/bin/oversip..."
      rm -f /usr/local/bin/oversip
    fi
    ;;

esac

exit 0

#DEBHELPER#
