#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

set -e


install_gem() {
  echo "installing 'oversip' Ruby Gem from local package..."
  # Install from the locally packaged gem file
  gem install /usr/share/oversip/oversip-*.gem --no-document
}

case "$1" in

  install)
    # Add a Debian system user/group called "oversip".
    adduser --quiet --system --group --disabled-password \
            --shell /bin/false --gecos "OverSIP" \
            --home /var/run/oversip oversip || true

    # Install the Ruby gem.
    install_gem
    ;;

  upgrade)
    # Install the Ruby gem.
    install_gem
    ;;

esac

exit 0

#DEBHELPER#
