#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

set -e

case "$1" in

  install)
    # Add a Debian system user/group called "oversip".
    adduser --quiet --system --group --disabled-password \
            --shell /bin/false --gecos "OverSIP" \
            --home /var/run/oversip oversip || true
    ;;

  upgrade)
    # Nothing to do in preinst for upgrade
    ;;

esac

exit 0

#DEBHELPER#
